/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './app/__root'
import { Route as AppImport } from './app/_app'
import { Route as AppSearchIndexImport } from './app/_app/search/index'
import { Route as AppReelsIndexImport } from './app/_app/reels/index'
import { Route as AppProfileIndexImport } from './app/_app/profile/index'
import { Route as ApphomeIndexImport } from './app/_app/(home)/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppSearchIndexRoute = AppSearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => AppRoute,
} as any)

const AppReelsIndexRoute = AppReelsIndexImport.update({
  id: '/reels/',
  path: '/reels/',
  getParentRoute: () => AppRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)

const ApphomeIndexRoute = ApphomeIndexImport.update({
  id: '/(home)/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/(home)/': {
      id: '/_app/(home)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ApphomeIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/reels/': {
      id: '/_app/reels/'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/search/': {
      id: '/_app/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  ApphomeIndexRoute: typeof ApphomeIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppReelsIndexRoute: typeof AppReelsIndexRoute
  AppSearchIndexRoute: typeof AppSearchIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  ApphomeIndexRoute: ApphomeIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppReelsIndexRoute: AppReelsIndexRoute,
  AppSearchIndexRoute: AppSearchIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/': typeof ApphomeIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/reels': typeof AppReelsIndexRoute
  '/search': typeof AppSearchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof ApphomeIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/reels': typeof AppReelsIndexRoute
  '/search': typeof AppSearchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/(home)/': typeof ApphomeIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/reels/': typeof AppReelsIndexRoute
  '/_app/search/': typeof AppSearchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/profile' | '/reels' | '/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/profile' | '/reels' | '/search'
  id:
    | '__root__'
    | '/_app'
    | '/_app/(home)/'
    | '/_app/profile/'
    | '/_app/reels/'
    | '/_app/search/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/(home)/",
        "/_app/profile/",
        "/_app/reels/",
        "/_app/search/"
      ]
    },
    "/_app/(home)/": {
      "filePath": "_app/(home)/index.tsx",
      "parent": "/_app"
    },
    "/_app/profile/": {
      "filePath": "_app/profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/reels/": {
      "filePath": "_app/reels/index.tsx",
      "parent": "/_app"
    },
    "/_app/search/": {
      "filePath": "_app/search/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
